default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['MOVIES_API_DATABASE_HOSTNAME'] || 'localhost' %>
  username: <%= ENV['MOVIES_API_DATABASE_USERNAME'] || 'postgres'%>
  password: <%= ENV['MOVIES_API_DATABASE_PASSWORD'] || 'postgres'%>
  pool: 5

development:
  <<: *default
  database: movies_api_development
  
test:
  <<: *default
  database: movies_api_test

production:
  <<: *default
